"""create tables

Revision ID: 0f61b61bec03
Revises: 0c802937c700
Create Date: 2023-06-29 00:30:30.980408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f61b61bec03'
down_revision = '0c802937c700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.CheckConstraint('(first_name != last_name)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_reviews_customer_id_customers')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_reviews_hotel_id_hotels')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio2texts', schema=None) as batch_op:
        batch_op.alter_column('transcript_text',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('text2images', schema=None) as batch_op:
        batch_op.alter_column('prompt',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('text2texts', schema=None) as batch_op:
        batch_op.alter_column('transcript_text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text2texts', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('transcript_text',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('text2images', schema=None) as batch_op:
        batch_op.alter_column('prompt',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('audio2texts', schema=None) as batch_op:
        batch_op.alter_column('transcript_text',
               existing_type=sa.TEXT(),
               nullable=False)

    op.drop_table('reviews')
    op.drop_table('hotels')
    op.drop_table('customers')
    op.drop_table('audio')
    # ### end Alembic commands ###
