"""empty message

Revision ID: 15b8fb1a65a2
Revises: e1e3c5cc1b84
Create Date: 2023-06-30 10:20:34.694370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b8fb1a65a2'
down_revision = 'e1e3c5cc1b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio2texts', schema=None) as batch_op:
        batch_op.alter_column('audio_file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio2texts', schema=None) as batch_op:
        batch_op.alter_column('audio_file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
