"""empty message

Revision ID: 491a0659f48a
Revises: 0f61b61bec03
Create Date: 2023-06-30 03:07:25.249841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491a0659f48a'
down_revision = '0f61b61bec03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio2texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio2texts', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
