"""empty message

Revision ID: 5e0b1277c2ea
Revises: d0cfefa15416
Create Date: 2023-06-30 09:35:42.832678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0b1277c2ea'
down_revision = 'd0cfefa15416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
