"""empty message

Revision ID: a258e6776e01
Revises: 
Create Date: 2023-06-30 06:19:15.423095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a258e6776e01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio2texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_data', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('data')

    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.drop_column('audio_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_data', sa.BLOB(), nullable=True))

    with op.batch_alter_table('audio2texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.BLOB(), nullable=True))
        batch_op.drop_column('audio_data')

    # ### end Alembic commands ###
