"""empty message

Revision ID: b5f89d80ec8b
Revises: 1e57e4c02976
Create Date: 2023-06-30 09:20:25.470995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f89d80ec8b'
down_revision = '1e57e4c02976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
