"""empty message

Revision ID: e04b96c73b73
Revises: 
Create Date: 2023-06-27 18:14:12.291642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04b96c73b73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio2texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=500), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_file_path')
    )
    op.create_table('text2images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text2texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text2texts')
    op.drop_table('text2images')
    op.drop_table('audio2texts')
    # ### end Alembic commands ###
