"""empty message

Revision ID: f48c84581f1d
Revises: 15b8fb1a65a2
Create Date: 2023-07-01 14:53:31.450112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48c84581f1d'
down_revision = '15b8fb1a65a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio2texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translation_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio2texts', schema=None) as batch_op:
        batch_op.drop_column('translation_text')

    # ### end Alembic commands ###
